name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb3c17433e9d1b3e0922c709aaf04099efec1da9709c07b70150d17ae99be727"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
datapack-folder = "resources/common/required"
