name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b54accfaf15703ae1e2feb12a0ef31c891d424c47c6aeb00f6f94361370a7043"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
datapack-folder = "resources/common/required"
